# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
tyler = User.create!(username: 'westerman', email: 'westerantyler@gmail.com', real_name: 'tyler', blog_name: 'westerman',
                    city: 'San Francisco', country: 'US', password: 'voidpass1')

other = User.create!(username: 'otherguy', email: 'otherguy@gmail.com', real_name: 'realguy', blog_name: 'very real guy',
                    city: 'San Jose', country: 'US', password: 'voidpass2')

other2 = User.create!(username: 'superman12', email: 'superman12@gmail.com', real_name: 'clark', blog_name: 'superblog',
                    city: 'San Jose', country: 'US', password: 'voidpass3')

Post.create!(user_id: tyler.id, title: 'first post', content: 'this is the first post', num_recommends: 0, topic: 'admin')

Post.create!(user_id: tyler.id, title: 'Second Post', content: '###Lorem ipsum\n dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', num_recommends: 0, topic: 'admin')
Post.create!(user_id: tyler.id, title: 'Third Post', content: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?', num_recommends: 2, topic: 'admin')
Post.create!(user_id: other.id, title: 'Other Post 1', content: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?', num_recommends: 2, topic: 'test')
Post.create!(user_id: other.id, title: 'Other Post 2', content: "#Leggings Cliche Direct\n\n##Trade Trust Fund,\n\n###Jean Shorts Single-Origin Coffee\n\nfour loko Carles squid street art American Apparel selvage raw denim. Banh mi chillwave lumbersexual flexitarian Marfa. Four dollar toast crucifix tilde, Truffaut paleo Cosby sweater XOXO master cleanse Shoreditch disrupt.\n\nVegan church-key High Life photo booth freegan, tofu cred pork belly pickled craft beer gastropub vinyl food truck brunch. Scenester locavore master cleanse Brooklyn wayfarers crucifix pour-over. Disrupt yr Odd Future, Shoreditch authentic crucifix umami. Taxidermy +1 plaid, authentic fap hella pug. Stumptown crucifix literally, lomo Tonx PBR&B swag photo booth tousled.\n\nCliche brunch taxidermy, messenger bag pop-up tattooed Vice Pinterest heirloom ennui swag. Fixie four dollar toast Blue Bottle 3 wolf moon, cornhole quinoa next level kitsch Tumblr sartorial shabby chic. Ennui pug distillery occupy, tilde actually letterpress small batch gastropub fingerstache meh meditation four dollar toast.\n\nFixie blog letterpress viral locavore salvia. Ethical craft beer 8-bit polaroid, Blue Bottle PBR VHS skateboard locavore Intelligentsia plaid cliche. Lumbersexual Shoreditch gluten-free, keytar freegan irony wayfarers Bushwick McSweeney's Helvetica literally paleo jean shorts tote bag.Food truck beard street art 3 wolf moon mustache. Selvage ugh direct trade VHS readymade, taxidermy health goth Neutra butcher fixie master cleanse XOXO Vice. American Apparel cred Thundercats iPhone.\n\n##Ugh Synth Bespoke\n\nEtsy meggings occupy paleo art party flannel cronut XOXO cornhole. PBR&B messenger bag wolf Echo Park Odd Future lomo. Craft beer keytar readymade, next level jean shorts lomo narwhal butcher chia squid brunch sustainable cray Vice. Actually DIY PBR twee.Bushwick next level lumbersexual locavore bitters. Paleo cronut hoodie Truffaut, Odd Future leggings kale chips fap freegan art party. Pickled whatever gluten-free, Helvetica meggings actually church-key tofu butcher hella drinking vinegar. Ennui paleo artisan scenester tofu, asymmetrical trust fund. Craft beer kitsch Cosby sweater, chillwave Pinterest +1 typewriter Truffaut fanny pack distillery put a bird on it. Brooklyn small batch street art before they sold out, butcher meggings keffiyeh American Apparel. Occupy aesthetic listicle, salvia Tumblr farm-to-table deep v readymade health goth locavore.", num_recommends: 2, topic: 'test')

Following.create!(user_id: tyler.id, follow_id: other.id)
Following.create!(user_id: other.id, follow_id: tyler.id)

Bookmarking.create!(user_id: tyler.id, post_id: 3)
